In [91]:
import torch
import torch.nn.functional as F
import time
actions = torch.Tensor([[2,4,5,2,3,1,0],[1,1,1,1,1,1,0]])
actions = F.softmax(actions, dim=1)
actions.multinomial(7)

tensor([[2, 1, 4, 5, 3, 0, 6],
        [6, 3, 5, 2, 4, 1, 0]])

In [100]:
actions = torch.Tensor([1,1,1,1,1,1,0])
actions = F.softmax(actions, dim=0)
print(actions)
actions.multinomial(1).numpy()

tensor([0.1570, 0.1570, 0.1570, 0.1570, 0.1570, 0.1570, 0.0578])


array([2])

In [122]:
from typing import List, Tuple
Action = int
Point = Tuple[float, float]
obj1: Point = (112.4,22.5)
obj2: Point = (112.44, 22.55)
obs: List[Point] = [(112.6, 22.3), (112.5, 22.6)]
ob = (obj1, obs)

def gt() -> Point:
    x = 6
    return Action(x)
x = gt()
print(type(x)) 

<class 'int'>


In [48]:
import numpy as np
A= np.array([0,1,2])
B= np.array([[0, 1, 2, 3],
            [4, 5, 6, 7],
            [8, 9, 10, 11],])
np.einsum('i,ij->i', A, B)


array([ 0, 22, 76])

In [43]:
import pandas as pd
df = pd.DataFrame([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]], columns=["col1", "col2", "col3", "col4"])
df.mean(axis=0)

col1    2.0
col2    2.0
col3    2.0
col4    2.0
dtype: float64

In [39]:
df.drop(['col2', 'col4'], axis=1)

col1  col3
0     1     1
1     2     2
2     3     3