In [3]:
a = [1, 2, 3]
b = [3, 4, 6]
c = [8, 4, 9, 3, 7]

In [8]:
for x in zip(a, c):
    print(x)

(1, 8)
(2, 4)
(3, 9)


In [17]:
y = [(2, 5), (6, 7), (0, 5)]
x, z = zip(*y)
print(x, z)

(2, 6, 0) (5, 7, 5)


In [70]:
import torch.nn.functional as F
import torch
from torch.distributions import Categorical
probs = torch.tensor([[3.4, 5, 6.7, 9.0], [3.4, 5, 6.7, 9.0]])



In [28]:
print(F.log_softmax(probs, dim=1))
log_probs = F.log_softmax(probs, dim=1)

tensor([[-5.7154, -4.1154, -2.4154, -0.1154],
        [-5.7154, -4.1154, -2.4154, -0.1154]])


In [29]:
x = log_probs.gather

In [38]:

a = torch.arange(27, 89).view(2, 31)
a

tensor([[27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
         45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57],
        [58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
         76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88]])

In [66]:
b = torch.zeros(1, 31, dtype=int)
b[0][1] = 1
b

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]])

In [67]:
a.gather(1, b)

tensor([[27, 28, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
         27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27]])

In [118]:
probs = torch.FloatTensor([1.1, 1.2, 1.3, 1.5])
dist = Categorical(probs)
action = dist.sample()

In [120]:
print(action)
action_log_probs = num.log_prob(action)

tensor(0)


In [121]:
action_log_probs

tensor(-1.5339)

In [122]:
log_probs = F.log_softmax(probs, dim=0)
log_probs

tensor([-1.5724, -1.4724, -1.3724, -1.1724])

In [142]:
def make_env():
    def _thunk():
        env = gym.make(env_name)
        return env
    return _thunk

In [143]:
envs = [make_env() for _ in range(8)]

In [144]:
print(envs)

[<function make_env.<locals>._thunk at 0x7f5b3a2a8a60>, <function make_env.<locals>._thunk at 0x7f5a0ffdb670>, <function make_env.<locals>._thunk at 0x7f5a0ffdb040>, <function make_env.<locals>._thunk at 0x7f5a0ffdbc10>, <function make_env.<locals>._thunk at 0x7f5a0ffdb280>, <function make_env.<locals>._thunk at 0x7f5a0ffdb550>, <function make_env.<locals>._thunk at 0x7f5a0ffdbd30>, <function make_env.<locals>._thunk at 0x7f5a0ffdbee0>]
